/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package red.social;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import static red.social.FileManager.FRIENDS_FILE;
import static red.social.FileManager.SEPARADOR;
import static red.social.FileManager.pSEPARADOR;
import red.social.Icons.ListIcon;
/**
 *
 * @author Krle__000
 */
public class ExternMessages extends javax.swing.JFrame
{
   DefaultListModel messagesList = new DefaultListModel();
   public Profile myProfile;
   public String myUser;
   /**
    * Creates new form ExternMessages
    */
   public ExternMessages()
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_message = new javax.swing.JTextArea();
        lbl_Galery1 = new javax.swing.JLabel();
        btn_Enviar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_messagesList = new javax.swing.JList<>();
        lbl_Galery2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_Return = new javax.swing.JLabel();
        lbl_Galery4 = new javax.swing.JLabel();
        txt_receptor = new javax.swing.JTextField();
        sp_count = new javax.swing.JSpinner();
        lbl_Galery3 = new javax.swing.JLabel();
        btn_Recargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 160, 166));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red/social/Icons/printRight.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red/social/Icons/printLeft.png"))); // NOI18N

        txt_message.setBackground(new java.awt.Color(204, 204, 255));
        txt_message.setColumns(20);
        txt_message.setFont(new java.awt.Font("Century Schoolbook", 0, 10)); // NOI18N
        txt_message.setRows(5);
        txt_message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_messageKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(txt_message);

        lbl_Galery1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_Galery1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Galery1.setText("Escríbele a otro usuario");

        btn_Enviar.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btn_Enviar.setText("Enviar");
        btn_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnviarActionPerformed(evt);
            }
        });

        jl_messagesList.setBackground(new java.awt.Color(253, 211, 92));
        jl_messagesList.setFont(new java.awt.Font("Century Schoolbook", 0, 10)); // NOI18N
        jScrollPane6.setViewportView(jl_messagesList);

        lbl_Galery2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_Galery2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Galery2.setText("Mensajes recibidos:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 74, 117));
        jLabel2.setText("Comparte con tus amigos Lynx!");

        lbl_Return.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        lbl_Return.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Return.setText("Regresar");
        lbl_Return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ReturnMouseClicked(evt);
            }
        });

        lbl_Galery4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_Galery4.setForeground(new java.awt.Color(255, 255, 255));

        lbl_Galery3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_Galery3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Galery3.setText("Número de grupo");

        btn_Recargar.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        btn_Recargar.setText("Recargar mensajes");
        btn_Recargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RecargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Galery4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_Galery1)
                            .addGap(18, 18, 18)
                            .addComponent(txt_receptor))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_Galery3)
                            .addGap(18, 18, 18)
                            .addComponent(sp_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Galery2)
                    .addComponent(btn_Recargar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Return))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_Galery1)
                                    .addComponent(txt_receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_Enviar)
                                    .addComponent(sp_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Galery3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Galery4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Galery2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Recargar)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void showMessages(){
        
        messagesList.clear();
        jl_messagesList.setModel(messagesList);
       RedSocial.showMessages(messagesList, jl_messagesList, RedSocial.ACTUALUSER, true, true);
   }
    
    private void txt_messageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_messageKeyTyped
        // TODO add your handling code here:
        if(txt_message.getText().length()>= 140){
            evt.consume();
        }
    }//GEN-LAST:event_txt_messageKeyTyped

    private void btn_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnviarActionPerformed
       try {
           // TODO add your handling code here:
           Singleton.getInstancia().Insert(4, Integer.parseInt(sp_count.getValue().toString()), myUser, txt_receptor.getText(), txt_message.getText());
           txt_message.setText("");
           this.showMessages();
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(ExternMessages.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(ExternMessages.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btn_EnviarActionPerformed

    private void lbl_ReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ReturnMouseClicked
        // TODO add your handling code here:
        myProfile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_ReturnMouseClicked

    private void btn_RecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RecargarActionPerformed
        this.showMessages();
    }//GEN-LAST:event_btn_RecargarActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(ExternMessages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(ExternMessages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(ExternMessages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(ExternMessages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new ExternMessages().setVisible(true);
         }
      });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Enviar;
    private javax.swing.JButton btn_Recargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<String> jl_messagesList;
    private javax.swing.JLabel lbl_Galery1;
    private javax.swing.JLabel lbl_Galery2;
    private javax.swing.JLabel lbl_Galery3;
    private javax.swing.JLabel lbl_Galery4;
    private javax.swing.JLabel lbl_Return;
    private javax.swing.JSpinner sp_count;
    private javax.swing.JTextArea txt_message;
    private javax.swing.JTextField txt_receptor;
    // End of variables declaration//GEN-END:variables
}
