/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package red.social;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import static red.social.RedSocial.Background;
import static red.social.RedSocial.SEPARADOR;
/**
 *
 * @author Krle__000
 */
public class Profile extends javax.swing.JFrame {

    
    /**
     * Creates new form Profile
     * @param data
     */
    public Profile() {
        initComponents();
        this.getContentPane().setBackground(Background);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
           
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jScrollPane3 = new javax.swing.JScrollPane();
      jTextArea2 = new javax.swing.JTextArea();
      jPanel1 = new javax.swing.JPanel();
      lbl_profilePic = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      lbl_user = new javax.swing.JLabel();
      lbl_rol = new javax.swing.JLabel();
      txt_userInfo = new javax.swing.JTextField();
      txt_rolInfo = new javax.swing.JTextField();
      lbl_descripcion = new javax.swing.JLabel();
      jScrollPane2 = new javax.swing.JScrollPane();
      txt_descripcionInfo = new javax.swing.JTextArea();
      lbl_SesionOut = new javax.swing.JLabel();
      lbl_OutAccount = new javax.swing.JLabel();
      btn_settings = new javax.swing.JButton();

      jTextArea2.setColumns(20);
      jTextArea2.setRows(5);
      jScrollPane3.setViewportView(jTextArea2);

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setResizable(false);

      jPanel1.setBackground(new java.awt.Color(242, 132, 35));

      lbl_profilePic.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
      lbl_profilePic.setText("Foto");

      jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
      jLabel1.setText("PERFIL");

      lbl_user.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
      lbl_user.setText("Usuario");

      lbl_rol.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
      lbl_rol.setText("Rol");

      txt_userInfo.setEditable(false);
      txt_userInfo.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
      txt_userInfo.setText("jTextField1");

      txt_rolInfo.setEditable(false);
      txt_rolInfo.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
      txt_rolInfo.setText("jTextField1");

      lbl_descripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
      lbl_descripcion.setText("Descripción");

      txt_descripcionInfo.setEditable(false);
      txt_descripcionInfo.setColumns(20);
      txt_descripcionInfo.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
      txt_descripcionInfo.setRows(5);
      jScrollPane2.setViewportView(txt_descripcionInfo);

      lbl_SesionOut.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
      lbl_SesionOut.setText("Cerrar Sesión");
      lbl_SesionOut.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            lbl_SesionOutMouseClicked(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(45, 45, 45)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(lbl_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbl_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lbl_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(55, 55, 55)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
               .addComponent(txt_rolInfo)
               .addComponent(lbl_profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txt_userInfo))
            .addContainerGap(195, Short.MAX_VALUE))
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_SesionOut, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(lbl_SesionOut))
            .addGap(17, 17, 17)
            .addComponent(lbl_profilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lbl_user)
               .addComponent(txt_userInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lbl_rol)
               .addComponent(txt_rolInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(lbl_descripcion)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(113, Short.MAX_VALUE))
      );

      lbl_OutAccount.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
      lbl_OutAccount.setText("Cerrar cuenta");
      lbl_OutAccount.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            lbl_OutAccountMouseClicked(evt);
         }
      });

      btn_settings.setMaximumSize(new java.awt.Dimension(25, 25));
      btn_settings.setMinimumSize(new java.awt.Dimension(25, 25));
      btn_settings.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            btn_settingsMouseClicked(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(45, 45, 45)
                  .addComponent(btn_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(lbl_OutAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(btn_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGap(18, 18, 18)))
            .addComponent(lbl_OutAccount)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents
    
    public void ShowInfo(String data){
       if(data.split(Pattern.quote(SEPARADOR))[4].equals("1")){
          lbl_OutAccount.setVisible(false);
       }
        btn_settings.setIcon(new ImageIcon((new ImageIcon("src\\red\\social\\Icons\\settings.png")).getImage().getScaledInstance(23, 23,  java.awt.Image.SCALE_SMOOTH)));
        String userInformation[] = data.split(Pattern.quote(SEPARADOR));
        txt_userInfo.setText(userInformation[0]);
        lbl_profilePic.setIcon(new ImageIcon((new ImageIcon(userInformation[8])).getImage().getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH)));
        if (userInformation[4].equals("1"))
            txt_rolInfo.setText("Administrador");
        else
            txt_rolInfo.setText("No Administrador");
        txt_descripcionInfo.setText(userInformation[9]); 
    }
    
    private void btn_settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingsMouseClicked
        // TODO add your handling code here:
        String actualUser[] = FileManager.Search(RedSocial.ACTUALUSER).split(Pattern.quote(SEPARADOR));
        
        // Si el usuario no es administrador le muestra su menu donde se le indica lo que puede hacer 
        if ("0".equals(actualUser[4])){
            InformationEdit editMyInfo = new InformationEdit();
            editMyInfo.ShowInformation(RedSocial.ACTUALUSER);
            editMyInfo.setVisible(true); 
        }
        
        // Si ES administrador se le muestra el menu donde se le muestra lo que puede ha
        else{
            RedSocial.SettingsAdminController();
            this.dispose();
        }
            
        
    }//GEN-LAST:event_btn_settingsMouseClicked

   private void lbl_SesionOutMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_SesionOutMouseClicked
   {//GEN-HEADEREND:event_lbl_SesionOutMouseClicked
      // TODO add your handling code here:
      RedSocial.LoginController();
      this.dispose();
   }//GEN-LAST:event_lbl_SesionOutMouseClicked

   private void lbl_OutAccountMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_OutAccountMouseClicked
   {//GEN-HEADEREND:event_lbl_OutAccountMouseClicked
      // TODO add your handling code here:
       RedSocial.Delete(RedSocial.ACTUALUSER);
        RedSocial.ACTUALUSER = ""; // Vacio la variable de usuario actual porque se elimino cuenta
        this.dispose();
        RedSocial.LoginController();
   }//GEN-LAST:event_lbl_OutAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btn_settings;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JTextArea jTextArea2;
   private javax.swing.JLabel lbl_OutAccount;
   private javax.swing.JLabel lbl_SesionOut;
   private javax.swing.JLabel lbl_descripcion;
   private javax.swing.JLabel lbl_profilePic;
   private javax.swing.JLabel lbl_rol;
   private javax.swing.JLabel lbl_user;
   private javax.swing.JTextArea txt_descripcionInfo;
   private javax.swing.JTextField txt_rolInfo;
   private javax.swing.JTextField txt_userInfo;
   // End of variables declaration//GEN-END:variables
}
