/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package red.social;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import static red.social.FileManager.GaleryLength;
import static red.social.FileManager.IMAGE_FILE;
import static red.social.FileManager.SEPARADOR;
import sun.net.www.content.audio.x_aiff;
import static red.social.RedSocial.Fill;
/**
 *
 * @author Krle__000
 */
public class SeeImages extends javax.swing.JFrame
{

   /**
    * Creates new form SeeImages
    */
   public ArrayList<String> galery;
   public Profile myProfile;
   public String myUser;
   int actualPicture=0;
   
   public SeeImages()
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jPanel3 = new javax.swing.JPanel();
      lbl_PicturePath = new javax.swing.JLabel();
      lbl_DeleteImage = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      btn_right = new javax.swing.JButton();
      btn_left = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jPanel3.setBackground(new java.awt.Color(133, 25, 52));

      lbl_PicturePath.setText("jLabel5");

      lbl_DeleteImage.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
      lbl_DeleteImage.setForeground(new java.awt.Color(255, 255, 255));
      lbl_DeleteImage.setText("Borrar imagen");
      lbl_DeleteImage.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            lbl_DeleteImageMouseClicked(evt);
         }
      });

      jButton1.setBackground(new java.awt.Color(233, 25, 52));
      jButton1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
      jButton1.setForeground(new java.awt.Color(255, 255, 255));
      jButton1.setText("x");
      jButton1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButton1ActionPerformed(evt);
         }
      });

      btn_right.setBackground(new java.awt.Color(0, 102, 102));
      btn_right.setFont(new java.awt.Font("Yu Gothic Medium", 1, 11)); // NOI18N
      btn_right.setForeground(new java.awt.Color(255, 255, 255));
      btn_right.setText("▷");
      btn_right.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btn_rightActionPerformed(evt);
         }
      });

      btn_left.setBackground(new java.awt.Color(0, 102, 102));
      btn_left.setFont(new java.awt.Font("Yu Gothic Medium", 1, 11)); // NOI18N
      btn_left.setForeground(new java.awt.Color(255, 255, 255));
      btn_left.setText("◁");
      btn_left.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btn_leftActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(lbl_DeleteImage)
                     .addComponent(jButton1)))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addGap(191, 191, 191)
                  .addComponent(btn_left)
                  .addGap(91, 91, 91)
                  .addComponent(btn_right)
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(74, 74, 74)
            .addComponent(lbl_PicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(75, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jButton1)
            .addGap(18, 18, 18)
            .addComponent(lbl_PicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn_left, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn_right, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
            .addComponent(lbl_DeleteImage)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 555, Short.MAX_VALUE)
         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
               .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(0, 0, Short.MAX_VALUE)))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 482, Short.MAX_VALUE)
         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
   {//GEN-HEADEREND:event_jButton1ActionPerformed
      // TODO add your handling code here:
      myProfile.setVisible(true);
      this.dispose();
   }//GEN-LAST:event_jButton1ActionPerformed

   private void btn_leftActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_leftActionPerformed
   {//GEN-HEADEREND:event_btn_leftActionPerformed
      // TODO add your handling code here:
      ToLeft();
   }//GEN-LAST:event_btn_leftActionPerformed

   private void lbl_DeleteImageMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbl_DeleteImageMouseClicked
   {//GEN-HEADEREND:event_lbl_DeleteImageMouseClicked
      // TODO add your handling code here:
      try{
         Path PathToDelete = Paths.get(galery.get(actualPicture));
      Files.delete(PathToDelete);
      }catch(Exception e){
         
      }
      FileManager.Update(IMAGE_FILE, RegisterToDelete(galery.get(actualPicture)));
      galery.removeIf(x -> x.equals(actualPicture));
      if(galery.isEmpty()){
         lbl_PicturePath.setIcon(null);
      }else{
         ToRight();
      }
      
      //revome del file manager
   }//GEN-LAST:event_lbl_DeleteImageMouseClicked

   private void btn_rightActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_rightActionPerformed
   {//GEN-HEADEREND:event_btn_rightActionPerformed
      // TODO add your handling code here:
      ToRight();
   }//GEN-LAST:event_btn_rightActionPerformed

   public void ChangePicture(int position){
      try{
      lbl_PicturePath.setText("");
      lbl_PicturePath.setIcon(new ImageIcon((new ImageIcon(galery.get(position))).getImage().getScaledInstance(171, 147,  java.awt.Image.SCALE_SMOOTH)));
      }catch(Exception e){
         
      }
   }
   
   public void ToRight(){
      if(!galery.isEmpty()){
         if(actualPicture+1 == galery.size()){
            actualPicture=0;
         }else{
            actualPicture++;
         }
         ChangePicture(actualPicture);
      }
   }
   
   public void ToLeft(){
       if(!galery.isEmpty()){
         if(actualPicture-1 == -1){
            actualPicture = galery.size()-1;
         }else{
            actualPicture--;
         }
         ChangePicture(actualPicture);
      }
   }
   public String RegisterToDelete(String path){
      return  Fill(myUser + SEPARADOR + path + SEPARADOR + new SimpleDateFormat("dd/MM/yyyy").format(new Date()) + SEPARADOR + "0", GaleryLength);
   }
   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(SeeImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(SeeImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(SeeImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(SeeImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new SeeImages().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btn_left;
   private javax.swing.JButton btn_right;
   private javax.swing.JButton jButton1;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JLabel lbl_DeleteImage;
   private javax.swing.JLabel lbl_PicturePath;
   // End of variables declaration//GEN-END:variables
}
