package red.social;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import java.text.SimpleDateFormat; 
import javax.swing.JFileChooser;
import java.util.regex.Pattern;
import java.util.GregorianCalendar;
import static red.social.FileManager.SEPARADOR;
import static red.social.FileManager.BackupLength;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Oscar
 */
public class SettingsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form SettingsAdmin
     */
    public SettingsAdmin() {
        initComponents();
        lbl_ReorganizeSuccess.setVisible(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        btn_Delete.setEnabled(false);
        btn_Modify.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jPanel1 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      jPanel3 = new javax.swing.JPanel();
      btn_ModifyInformation = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      btn_DoBackup = new javax.swing.JButton();
      btn_Return = new javax.swing.JButton();
      jPanel4 = new javax.swing.JPanel();
      jLabel4 = new javax.swing.JLabel();
      btn_EnterUsers = new javax.swing.JButton();
      jLabel3 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      btn_Reorganize = new javax.swing.JButton();
      lbl_ReorganizeSuccess = new javax.swing.JLabel();
      jPanel5 = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      txt_Search = new javax.swing.JTextField();
      btn_Find = new javax.swing.JButton();
      btn_Modify = new javax.swing.JButton();
      btn_Delete = new javax.swing.JButton();
      lbl_usuario = new javax.swing.JLabel();

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
      );

      setUndecorated(true);
      setResizable(false);

      jPanel2.setBackground(new java.awt.Color(55, 160, 166));

      jPanel3.setBackground(new java.awt.Color(253, 211, 92));

      btn_ModifyInformation.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      btn_ModifyInformation.setForeground(new java.awt.Color(71, 79, 89));
      btn_ModifyInformation.setText("Ir");
      btn_ModifyInformation.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            btn_ModifyInformationMouseClicked(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      jLabel1.setForeground(new java.awt.Color(71, 79, 89));
      jLabel1.setText("Modificar Información");

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addGap(42, 42, 42)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 637, Short.MAX_VALUE)
            .addComponent(btn_ModifyInformation)
            .addGap(191, 191, 191))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btn_ModifyInformation)
               .addComponent(jLabel1))
            .addContainerGap(31, Short.MAX_VALUE))
      );

      jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      jLabel2.setForeground(new java.awt.Color(71, 79, 89));
      jLabel2.setText("Realizar Backup");

      btn_DoBackup.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      btn_DoBackup.setForeground(new java.awt.Color(71, 79, 89));
      btn_DoBackup.setText("Ir");
      btn_DoBackup.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btn_DoBackupActionPerformed(evt);
         }
      });

      btn_Return.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      btn_Return.setForeground(new java.awt.Color(71, 79, 89));
      btn_Return.setText("Regresar");
      btn_Return.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            btn_ReturnMouseClicked(evt);
         }
      });

      jPanel4.setBackground(new java.awt.Color(253, 211, 92));

      jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      jLabel4.setForeground(new java.awt.Color(71, 79, 89));
      jLabel4.setText("Ingresar Nuevos Usuarios");

      btn_EnterUsers.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      btn_EnterUsers.setForeground(new java.awt.Color(71, 79, 89));
      btn_EnterUsers.setText("Ir");
      btn_EnterUsers.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            btn_EnterUsersMouseClicked(evt);
         }
      });

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 672, Short.MAX_VALUE)
            .addComponent(btn_EnterUsers)
            .addGap(186, 186, 186))
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(btn_EnterUsers)
               .addComponent(jLabel4))
            .addContainerGap(41, Short.MAX_VALUE))
      );

      jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
      jLabel3.setForeground(new java.awt.Color(255, 255, 255));
      jLabel3.setText("Funciones Lynx");

      jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      jLabel6.setForeground(new java.awt.Color(71, 79, 89));
      jLabel6.setText("Reorganizar todos los archivos");

      btn_Reorganize.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      btn_Reorganize.setForeground(new java.awt.Color(71, 79, 89));
      btn_Reorganize.setText("Reorganizar");
      btn_Reorganize.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btn_ReorganizeActionPerformed(evt);
         }
      });

      lbl_ReorganizeSuccess.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      lbl_ReorganizeSuccess.setForeground(new java.awt.Color(255, 255, 255));
      lbl_ReorganizeSuccess.setText("Se ha realizado con éxito");

      jPanel5.setBackground(new java.awt.Color(253, 211, 92));

      jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      jLabel5.setForeground(new java.awt.Color(71, 79, 89));
      jLabel5.setText("Buscar Usuarios");

      txt_Search.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
      txt_Search.setForeground(new java.awt.Color(71, 79, 89));

      btn_Find.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      btn_Find.setForeground(new java.awt.Color(71, 79, 89));
      btn_Find.setText("Buscar");
      btn_Find.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            btn_FindMouseClicked(evt);
         }
      });

      btn_Modify.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      btn_Modify.setForeground(new java.awt.Color(71, 79, 89));
      btn_Modify.setText("Modificar");
      btn_Modify.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            btn_ModifyMouseClicked(evt);
         }
      });

      btn_Delete.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
      btn_Delete.setForeground(new java.awt.Color(71, 79, 89));
      btn_Delete.setText("Eliminar");
      btn_Delete.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            btn_DeleteMouseClicked(evt);
         }
      });

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addComponent(jLabel5)
            .addGap(18, 18, 18)
            .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_Find)
            .addGap(187, 187, 187)
            .addComponent(btn_Modify)
            .addGap(35, 35, 35)
            .addComponent(btn_Delete)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btn_Find)
               .addComponent(btn_Modify)
               .addComponent(btn_Delete))
            .addContainerGap(35, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(42, 42, 42)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_DoBackup)
            .addGap(189, 189, 189))
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 0, Short.MAX_VALUE))
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel3)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_ReorganizeSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btn_Reorganize)
            .addGap(181, 181, 181))
         .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Return)
            .addGap(45, 45, 45))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(jLabel3)
            .addGap(18, 18, 18)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(31, 31, 31)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(btn_DoBackup))
            .addGap(34, 34, 34)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(33, 33, 33)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(lbl_ReorganizeSuccess)
               .addComponent(btn_Reorganize))
            .addGap(37, 37, 37)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_Return)
            .addContainerGap(32, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl_usuario))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void btn_ReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReturnMouseClicked
        // TODO add your handling code here:
        String actualUser = FileManager.SearchUser(RedSocial.ACTUALUSER);
        RedSocial.ProfileController(actualUser);
        this.dispose();
    }//GEN-LAST:event_btn_ReturnMouseClicked

    private void btn_FindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FindMouseClicked
        // TODO add your handling code here:
        String userToSearch = FileManager.SearchUser(txt_Search.getText());
        
        
        if (userToSearch != null){
        String userToSearchArray[] = userToSearch.split(Pattern.quote(SEPARADOR));
            if (userToSearchArray[10].equals("1")  /*Primero vemos si esta activo*/
                && !userToSearchArray[0].equals(RedSocial.ACTUALUSER) /*Despues vemos si es igual al usuarioActual*/
                && userToSearchArray[4].equals("0")) /*Por ultimo revisamos si es usuario*/ /*Para comparar strings mejor usar equals*/{           
                lbl_usuario.setText("Si existe.");
                btn_Delete.setEnabled(true);
                btn_Modify.setEnabled(true);
            }
            /*Si el usuario que se busco es igual al usuario que esta
            usando el sistema solo muestra que si existe*/            
            else if (userToSearchArray[0].equals(RedSocial.ACTUALUSER))
            {
                lbl_usuario.setText("Si existe.");
            }
            /*Si el usuario que se busco esta activo y es administrador solo se puede modificar pero no eliminar*/
            else if (userToSearchArray[10].equals("1")
                     && userToSearchArray[4].equals("1")){
                lbl_usuario.setText("Si existe.");
                btn_Modify.setEnabled(true);
            }
        }
        else
        {
            lbl_usuario.setText("No existe");
            btn_Modify.setEnabled(false);
            btn_Delete.setEnabled(false);
        }            
    }//GEN-LAST:event_btn_FindMouseClicked

    private void btn_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseClicked
        // TODO add your handling code here:
        RedSocial.Delete(txt_Search.getText());
        txt_Search.setText("");
    }//GEN-LAST:event_btn_DeleteMouseClicked

    private void btn_ModifyInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModifyInformationMouseClicked
        // TODO add your handling code here:
        InformationEdit edit = new InformationEdit();
        edit.ShowInformation(RedSocial.ACTUALUSER);
        edit.isManager(true);
        edit.setVisible(true);
    }//GEN-LAST:event_btn_ModifyInformationMouseClicked

    private void btn_ModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModifyMouseClicked
        // TODO add your handling code here:
        
        InformationEdit edit = new InformationEdit();
        edit.ShowInformation(txt_Search.getText());
        edit.isManager(true);
        edit.setVisible(true);  
        txt_Search.setText("");
        btn_Delete.setEnabled(false);
        btn_Modify.setEnabled(false);
    }//GEN-LAST:event_btn_ModifyMouseClicked

    private void btn_EnterUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EnterUsersMouseClicked
        // TODO add your handling code here:
        RedSocial.RegisterController(true);
        this.dispose();
    }//GEN-LAST:event_btn_EnterUsersMouseClicked

   private void btn_DoBackupActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_DoBackupActionPerformed
   {//GEN-HEADEREND:event_btn_DoBackupActionPerformed
      // TODO add your handling code here:
      String PathBackup="";
      JFileChooser Chooser = new JFileChooser(); 
      Chooser.setCurrentDirectory(new java.io.File("."));
      //Chooser.setDialogTitle(choosertitle);
      Chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
      Chooser.setAcceptAllFileFilterUsed(false);    
      if (Chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
         PathBackup = Chooser.getSelectedFile().getAbsolutePath();
         FileManager.Backup(RedSocial.Fill(PathBackup +SEPARADOR+ RedSocial.ACTUALUSER +SEPARADOR+ Today(), BackupLength));
      }
   }//GEN-LAST:event_btn_DoBackupActionPerformed

   private void btn_ReorganizeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_ReorganizeActionPerformed
   {//GEN-HEADEREND:event_btn_ReorganizeActionPerformed
      // TODO add your handling code here:
      FileManager.Reorganize(RedSocial.ACTUALUSER);
      lbl_ReorganizeSuccess.setVisible(true);
   }//GEN-LAST:event_btn_ReorganizeActionPerformed

   private String Today(){
      Date fechaActual = new Date(); 
      SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
      return formato.format(fechaActual);
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsAdmin().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btn_Delete;
   private javax.swing.JButton btn_DoBackup;
   private javax.swing.JButton btn_EnterUsers;
   private javax.swing.JButton btn_Find;
   private javax.swing.JButton btn_Modify;
   private javax.swing.JButton btn_ModifyInformation;
   private javax.swing.JButton btn_Reorganize;
   private javax.swing.JButton btn_Return;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JLabel lbl_ReorganizeSuccess;
   private javax.swing.JLabel lbl_usuario;
   private javax.swing.JTextField txt_Search;
   // End of variables declaration//GEN-END:variables
}
